Update prisma-seed.md
Updated the seed command for the new one in the doc

> ERROR: "snaplet restore" is deprecated.
> Please use "snaplet snapshot restore" (snaplet ss r) instead.

It takes the latest snapshot and say yes to all, since we cannot interact with the CLI during the seed process.